### ISSUE TITLE
had to add $this->entity->attr

### ISSUE THREAD

**Issue by juanvillegas** [laracasts/Presenter#4]
In my presenter, to access the wrapped object's attribute I had to do it like:
![image](https://cloud.githubusercontent.com/assets/773149/2857020/3485bc9c-d172-11e3-9d72-6657ee66f26e.png)
In the example you are just doing $this->attr.. but it throws an exception because the attribute doesnt exist in $this, but in $this->entity

**Comment by deva7mad** [comment]
@TheGeekyM
